services:
  # frontend:
  # ... (configuration de votre service frontend)

  backend:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db_essencepascher

  db_essencepascher:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ~/apps/postgresql/db_essencepascher:/var/lib/postgresql/data
    ports:
      - 5433:5432
