name: build, test, and push docker images

on: pull_request

jobs: 
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Go to api and run tests
        run: cd api && npm i && npm run test

  docker:
    needs: test-api
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        

      - name: Push API image to Docker Hub
        uses: docker/build-push-action@v6.6.1
        with: 
          push: true
          context: "{{defaultContext}}:api"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/essencepascherapi:latest
    

    
