name: build, test, and push docker images

on: pull_request

jobs: 
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Go to api and run tests
        run: cd api && npm i && npm run test
        
      - name: Build API image
        working-directory: ./api
        run: docker build -t rthorski/essencepascherapi .
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push API image to Docker Hub
        uses: docker/build-push-action@v6.6.1
        with: 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/essencepascherapi:latest
    

    
